name: abujad_events
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  barcode_widget: ^2.0.4
  cached_network_image: ^3.3.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.0
  flutter_riverpod: ^2.4.9
  freezed_annotation: ^2.4.1
  go_router: ^14.1.0
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.3.8
  json_annotation: ^4.8.1
  lottie: ^2.6.0
  oktoast: ^3.4.0
  path_provider: ^2.1.2
  pretty_dio_logger: ^1.3.1
  provider: ^6.0.5
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  url_launcher: ^6.2.2

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.2
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/
